CREATE TABLE "STUDENT" (
"FIRSTNAME" VARCHAR(20),
"LASTNAME" VARCHAR(30),
"PSUID" VARCHAR(10) not null primary key,
"TEAM" INTEGER
);
INSERT INTO STUDENT VALUES ('MATTHEW','CAMPBELL','MRC5372',10);
INSERT INTO STUDENT VALUES ('EDWARD','JONES','EAJ5073',6);
INSERT INTO STUDENT VALUES ('TRENT','BALTA','TMB5577',12);
INSERT INTO STUDENT VALUES ('ALEXANDER','VALLO','ANV5067',2);
INSERT INTO STUDENT VALUES ('DAVID','KUBACKI','DMK5048',5);
INSERT INTO STUDENT VALUES ('AUSTIN','RAUSCH','AHR5067',12);
INSERT INTO STUDENT VALUES ('KIMBERLY','TAROSKY','KRT5110',1);
INSERT INTO STUDENT VALUES ('ZACHARY','REOTT','ZDR5023',6);
INSERT INTO STUDENT VALUES ('ANDREW','HANKEWYCZ','AZH5442',7);
INSERT INTO STUDENT VALUES ('TYLER','JACOBS','TAJ5130',7);
INSERT INTO STUDENT VALUES ('ZACHARY','OROSZ','ZJO5002',6);
INSERT INTO STUDENT VALUES ('MARK','STANKIEWICZ','MIS5708',9);
INSERT INTO STUDENT VALUES ('PETER','KALMAR','PJK5220',3);
INSERT INTO STUDENT VALUES ('CHARLIE','DUONG','CTD5100',9);
INSERT INTO STUDENT VALUES ('GARY','LIN','GQL5141',6);
INSERT INTO STUDENT VALUES ('SHAUN','SITTERLEY','SMS6179',4);
INSERT INTO STUDENT VALUES ('ANDREW','KRUZAN','ASK5264',4);
INSERT INTO STUDENT VALUES ('ARIN','REESE','AWR5319',11);
INSERT INTO STUDENT VALUES ('AUSTIN','KELLEHER','ALK5492',7);
INSERT INTO STUDENT VALUES ('MATTHEW','PANETTA','MDP5280',9);
INSERT INTO STUDENT VALUES ('ROBERT','HANSEN','RAH5360',8);
INSERT INTO STUDENT VALUES ('CHRISTOPHER','ROSSWOG','CMR5556',10);
INSERT INTO STUDENT VALUES ('GREGORY','LOUCHART','GDL5051',2);
INSERT INTO STUDENT VALUES ('DYLAN','TAYLOR','DMT5235',3);
INSERT INTO STUDENT VALUES ('AUSTIN','BAKER','ARB5671',3);
INSERT INTO STUDENT VALUES ('STEVEN','RISTAU','SPR5122',2);
INSERT INTO STUDENT VALUES ('JOSHUA','STEEN','JDS5782',9);
INSERT INTO STUDENT VALUES ('JAMES','KARSH','JRK5377',12);
INSERT INTO STUDENT VALUES ('BRIAN','RISTAU','BJR5336',2);
INSERT INTO STUDENT VALUES ('AMANDA','BALOS','AZB199',1);
INSERT INTO STUDENT VALUES ('DANIEL','GOGA','DRG5190',11);
INSERT INTO STUDENT VALUES ('JUSTIN','IVANCO','JJI5019',10);
INSERT INTO STUDENT VALUES ('DYLAN','POLJAK','DJP5319',4);
INSERT INTO STUDENT VALUES ('JAMES','SHULTZ','JTS5507',8);

