
package iGradeClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "iGrade", targetNamespace = "http://iGrade/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGrade {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toHundredScale", targetNamespace = "http://iGrade/", className = "iGradeClient.ToHundredScale")
    @ResponseWrapper(localName = "toHundredScaleResponse", targetNamespace = "http://iGrade/", className = "iGradeClient.ToHundredScaleResponse")
    @Action(input = "http://iGrade/iGrade/toHundredScaleRequest", output = "http://iGrade/iGrade/toHundredScaleResponse")
    public String toHundredScale(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toSevenScale", targetNamespace = "http://iGrade/", className = "iGradeClient.ToSevenScale")
    @ResponseWrapper(localName = "toSevenScaleResponse", targetNamespace = "http://iGrade/", className = "iGradeClient.ToSevenScaleResponse")
    @Action(input = "http://iGrade/iGrade/toSevenScaleRequest", output = "http://iGrade/iGrade/toSevenScaleResponse")
    public String toSevenScale(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toLetterScale", targetNamespace = "http://iGrade/", className = "iGradeClient.ToLetterScale")
    @ResponseWrapper(localName = "toLetterScaleResponse", targetNamespace = "http://iGrade/", className = "iGradeClient.ToLetterScaleResponse")
    @Action(input = "http://iGrade/iGrade/toLetterScaleRequest", output = "http://iGrade/iGrade/toLetterScaleResponse")
    public String toLetterScale(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
