
package iGradeClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "iGradeService", targetNamespace = "http://iGrade/", wsdlLocation = "http://localhost:8888/iGrade?wsdl")
public class IGradeService
    extends Service
{

    private final static URL IGRADESERVICE_WSDL_LOCATION;
    private final static WebServiceException IGRADESERVICE_EXCEPTION;
    private final static QName IGRADESERVICE_QNAME = new QName("http://iGrade/", "iGradeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/iGrade?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IGRADESERVICE_WSDL_LOCATION = url;
        IGRADESERVICE_EXCEPTION = e;
    }

    public IGradeService() {
        super(__getWsdlLocation(), IGRADESERVICE_QNAME);
    }

    public IGradeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IGRADESERVICE_QNAME, features);
    }

    public IGradeService(URL wsdlLocation) {
        super(wsdlLocation, IGRADESERVICE_QNAME);
    }

    public IGradeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IGRADESERVICE_QNAME, features);
    }

    public IGradeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IGradeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IGrade
     */
    @WebEndpoint(name = "iGradePort")
    public IGrade getIGradePort() {
        return super.getPort(new QName("http://iGrade/", "iGradePort"), IGrade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGrade
     */
    @WebEndpoint(name = "iGradePort")
    public IGrade getIGradePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://iGrade/", "iGradePort"), IGrade.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IGRADESERVICE_EXCEPTION!= null) {
            throw IGRADESERVICE_EXCEPTION;
        }
        return IGRADESERVICE_WSDL_LOCATION;
    }

}
